name: RevealSecurity CI / CD
on:
  push:
    branches:
      - "main"
jobs:
  docker-registry:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      
      - name: Build and push to local registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: 127.0.0.1:5000/name/app:latest
      
      - name: Inspect
        run: |
          docker buildx imagetools inspect 127.0.0.1:5000/name/app:latest
      
      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --insecure-registry 127.0.0.1:5000
      - name: Create Registry Secret
        run: |
          kubectl create secret generic regcred \
          --from-file=.dockerconfigjson=/home/runner/.docker/config.json \
          --type=kubernetes.io/dockerconfigjson
          
      - name: Deploy To K8S
        run: |
          kubectl apply -f deployment.yaml
      
      - name: Validate Service up
        run: |
          sleep 10
          kubectl describe pod 
          kubectl get deployments -A
          sleep 10
          kubectl get deployments -A
          sleep 10
          kubectl get po -o yaml
          curl localhost:80
