name: RevealSecurity CI / CD - Branch Master

on:
  workflow_dispatch:
  
jobs:
  deploy-helm-application:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        minikube start 
        
    - name: Deploy Helm Chart
      run: |
  
        helm upgrade --create-namespace --namespace test --install --debug --values ./nginx-phpfpm/values.yaml  my-release ./nginx-phpfpm

    - name: Validate Chart Deployed
      run: |
        kubectl delete service -n test my-release-nginx-phpfpm-nginx
        kubectl expose deployment my-release-nginx-phpfpm-nginx -n test --type=NodePort --name=nginx-phpfpm-node-port
        sleep 40
        podName=`kubectl get pods -n test --no-headers -o custom-columns=":metadata.name" | grep "phpfpm-nginx"`
        echo "podName: $podName"
        kubectl wait --for=condition=ready pod $podName -n test
        kubectl logs $podName -n test
        POD_HOST=`kubectl get pod -n test $podName --template '{{.status.podIP}}'`
        NODE_PORT=`kubectl describe services -n test nginx-phpfpm-node-port | grep "NodePort:"  | awk '{print $3}'`
        NODE_PORT=${NODE_PORT::-4}
        kubectl cluster-info
        minikube service nginx-phpfpm-node-port -n test --url
        EXT_IP=`minikube ip` 
        sleep 5
        curl --connect-timeout 10 -vki "$EXT_IP:$NODE_PORT/index.php" 
  
  build-and-push-application:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login Docker Hub
      run: |
        docker login -u "boazhalter" -p "${{ secrets.dockerhubpassword }}" docker.io
    
    - name: Build Docker Image
      run: |
          docker build . -t boazhalter/revealsecurity:latest
          
    - name: Push Docker Image
      run: |
        docker push boazhalter/revealsecurity:latest
        
