name: RevealSecurity CI / CD
on:
  push:
    branches:
      - "dockerfile"
jobs:        
  build-run-and-push-application:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login Docker Hub
      run: |
        docker login -u "boazhalter" -p "${{ secrets.dockerhubpassword }}" docker.io
    
    - name: Build Docker Image
      run: |
          docker build . -t boazhalter/revealsecurity:latest
    
    - name: Push Run Image
      run: |
        docker run -d -p 8080:80 --name nginx-php-fpm boazhalter/revealsecurity:latest
        docker wait nginx-php-fpm 

    - name: Test PHP
      run: |   
        docker logs nginx-php-fpm
        docker ps 
        docker inspect \
        --format '{{ .NetworkSettings.IPAddress }}' nginx-php-fpm
        
        docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' nginx-php-fpm
        
        ip=`docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' nginx-php-fpm`
        echo "ip=$ip"
        curl "http://$ip:8080/index.php"

    - name: Push Docker Image
      run: |
        docker push boazhalter/revealsecurity:latest
        
