name: ci

on:
  push:
    branches:
      - "main"
jobs:
  docker:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: Build and push to local registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: localhost:5000/name/app:latest
      - name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/name/app:latest
      - name: Check if Kubernetes cluster exists
        id: check_cluster
        run: |
          if kubectl get nodes >/dev/null 2>&1; then
            echo "::set-output name=cluster_exists::true"
          else
            echo "::set-output name=cluster_exists::false"
          fi
      - name: Install Minikube
        if: steps.check_cluster.outputs.cluster_exists == 'false'
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start
          kubectl get po -A


