name: Scripts CI

on:
  push:
    branches:
      - "scripts"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Run Script
        run: |
          fileOne="https://raw.githubusercontent.com/BoazHalter/RevealSecurity/main/.github/workflows/CI-CD.yml"
          fileTwo="https://github.com/BoazHalter/RevealSecurity/blob/dockerfile/.github/workflows/CI-CD.yml"
          bash run.sh merge $fileOne $fileTwo
          bash run.sh uniq $fileOne $fileTwo
          bash run.sh common $fileOne $fileTwo
          bash run.sh sort $fileOne $fileTwo
