name: Scripts CI

on:
  push:
    branches:
      - "scripts"
jobs:
  scripts-ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Fetchfiles
        run: |
          curl "https://raw.githubusercontent.com/BoazHalter/RevealSecurity/main/.github/workflows/CI-CD.yml" >> scripts/ymlOne.yaml
          curl "https://raw.githubusercontent.com/BoazHalter/RevealSecurity/dockerfile/.github/workflows/CI-CD.yml" >> scripts/ymlTwo.yaml

      - name: Run Script
        run: |
          cd scripts
          #yq -n 'load("./ymlOne.yaml") * load("./ymlTwo.yaml")'
          #bash run-yq.sh merge "./ymlOne.yaml" "./ymlTwo.yaml"
          #bash run-yq.sh unique "./ymlOne.yaml" "./ymlTwo.yaml"
          bash run-yq.sh common "ymlOne.yaml" "ymlTwo.yaml"
          #bash run-yq.sh sort scripts/ymlOne.yml scripts/ymlTwo.yml
