name: Scripts CI

on:
  push:
    branches:
      - "scripts"
jobs:
  scripts-ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Run Script
        run: |
          cd scripts
          fileOne="https://raw.githubusercontent.com/BoazHalter/RevealSecurity/main/.github/workflows/CI-CD.yml"
          fileTwo="https://raw.githubusercontent.com/BoazHalter/RevealSecurity/dockerfile/.github/workflows/CI-CD.yml"
          bash run-yq.sh merge $fileOne $fileTwo
          bash run-yq.sh uniq $fileOne $fileTwo
          bash run-yq.sh common $fileOne $fileTwo
          bash run-yq.sh sort $fileOne $fileTwo
