name: Scripts CI

on:
  push:
    branches:
      - "scripts"
jobs:
  scripts-ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Fetchfiles
        run: |
          curl "https://raw.githubusercontent.com/BoazHalter/RevealSecurity/main/.github/workflows/CI-CD.yml" >> scripts/ymlOne.yaml
          curl "https://raw.githubusercontent.com/BoazHalter/RevealSecurity/dockerfile/.github/workflows/CI-CD.yml" >> scripts/ymlTwo.yaml

      - name: Run Script
        run: |
          cd scripts
          diff -u <(yq eval-all '. as $item | select(type == "object") | keys_unsorted[] as $key | "\($key): \($item[$key])"' ymlOne.yaml | sort) <(yq eval-all '. as $item | select(type == "object") | keys_unsorted[] as $key | "\($key): \($item[$key])"' ymlTwo.yaml | sort) | grep '^ '

        #  yq eval-all 'select(fileIndex == 0) * select(fileIndex == 1)' ymlOne.yaml ymlTwo.yaml


          #yq eval-all 'select(fileIndex == 0 and . as $file1 | input | $file1 == .)' ymlOne.yaml ymlTwo.yaml | yq eval-all 'select(fileIndex == 0)' - | yq eval 'del(.. | .foo?)' - | jq -s add
          #bash run-yq.sh merge "./ymlOne.yaml" "./ymlTwo.yaml"
          #bash run-yq.sh unique "./ymlOne.yaml" "./ymlTwo.yaml"
          #bash run-yq.sh common "./ymlOne.yaml" "./ymlTwo.yaml"
          #bash run-yq.sh sort scripts/ymlOne.yml scripts/ymlTwo.yml
